/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_ndktutorial_fibnative_Fiblib.h>
/* Header for class com_ndktutorial_fibnative_Fiblib */


static jlong fib(jlong n)
{
  return n <= 0 ? 0 : n == 1 ? 1 : fib(n-1) + fib(n-2);
}


JNIEXPORT jlong JNICALL Java_com_ndktutorial_fibnative_Fiblib_fibNR
  (JNIEnv *env, jclass clazz, jlong n) {

    return fib(n);
}

/*
 * Class:     com_ndktutorial_fibnative_Fiblib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ndktutorial_fibnative_Fiblib_fibNI
  (JNIEnv *env, jclass clazz, jlong n){

      jlong prev = -1;
      jlong result = 1;
      jlong i;

      for(i=0;i<n;i++)
      {
         jlong sum = result+prev;
         prev = result;
         result = sum;
      }
      return result;

}
