/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndktutorial_fibnative_Fiblib */

#ifndef _Included_com_ndktutorial_fibnative_Fiblib
#define _Included_com_ndktutorial_fibnative_Fiblib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndktutorial_fibnative_Fiblib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ndktutorial_fibnative_Fiblib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ndktutorial_fibnative_Fiblib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ndktutorial_fibnative_Fiblib_fibNI
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
